apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.name}}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{.Values.name}}-svc
          servicePort: 3000
        path: {{.Values.pathPrefix}}/pm
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: {{.Values.name}}-{{.Values.environment}}-primary-git-sync-grpc
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
#     nginx.ingress.kubernetes.io/server-alias: ~{{.Values.domainPrefix}}policy-mgmt-git-sync-grpc-([a-z0-9-]+)\.harness\.io
#     # nginx.ingress.kubernetes.io/server-alias: ~{{.Values.domainPrefix}}git-sync-grpc-([a-z0-9-]+)\.harness\.io
#     {{- if .Values.serviceUpstream}}
#     nginx.ingress.kubernetes.io/service-upstream: "true"
#     nginx.ingress.kubernetes.io/upstream-vhost: {{.Values.name}}.{{.Values.namespace.name}}.svc.cluster.local
#     {{- end}}
# spec:
#   rules:
#   - host: "{{.Values.domainPrefix}}policy-mgmt-git-sync-grpc-{{.Values.environment}}.harness.io"
#     http:
#      paths:
#      - backend:
#           serviceName: {{.Values.name}}-svc
#           servicePort: git-sync-grpc
#        path: /
#   tls:
#    - hosts:
#       - "{{.Values.domainPrefix}}policy-mgmt-git-sync-grpc-{{.Values.environment}}.harness.io"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.name}}-{{.Values.environment}}-primary-git-sync-grpc
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/server-alias: ~{{.Values.domainPrefix}}pm-git-sync-grpc-([a-z0-9-]+)\.harness\.io
    {{- if .Values.serviceUpstream}}
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: {{.Values.name}}.{{.Values.namespace.name}}.svc.cluster.local
    {{- end}}
spec:
  rules:
  - host: "{{.Values.domainPrefix}}pm-git-sync-grpc-{{.Values.environment}}.harness.io"
    http:
     paths:
     - backend:
          serviceName: {{.Values.name}}-svc
          servicePort: git-sync-grpc
       path: /
  tls:
   - hosts:
      - "{{.Values.domainPrefix}}pm-git-sync-grpc-{{.Values.environment}}.harness.io"